esphome:
  name: megadesk
  friendly_name: megadesk
  includes:
    - megadesk.h
  on_boot: 
    priority: -100
    then:
      - delay: 1s
      - uart.write: "<C0.0."
      - delay: 1s
      - uart.write: "<R0.11."
      - delay: 1s
      - uart.write: "<R0.12."
      - delay: 1s
      - uart.write: "<T3000,64."
      - delay: 2s
      - uart.write: "<T2000,128."

esp8266:
  board: d1_mini

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "QqlM/FhHgLmy+P7csJXk/Uq3QNnmXQSlqJJ4Z9kdhf8="

ota:
  password: "47642f7c2efa778c1cb60336c772f97a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Megadesk Fallback Hotspot"
    password: "nWMK1hYEtYzE"

captive_portal:

web_server:
  port: 80

uart:
  id: uart_desk
  baud_rate: 115200
  tx_pin: D0
  rx_pin: D1

sensor:
  - platform: custom
    lambda: |-
      auto megadesk = new Megadesk(id(uart_desk));
      App.register_component(megadesk);
      return { megadesk->raw_height, megadesk->min_height, megadesk->max_height, megadesk->audio };
    sensors:
      - id: megadesk_raw
        name: "Megadesk Raw"
        internal: true
        on_value:
          then:
            - component.update: megadesk_height_cm
            - component.update: megadesk_height_raw
      - name: "Megadesk Minimum Height"
        id: megadesk_min_height
      - name: "Megadesk Maximum Height"
        id: megadesk_max_height
      - name: "Megadesk Audio Enabled (raw)"
        id: megadesk_audio_enabled_raw
        internal: true

binary_sensor:
  - platform: template
    name: "Megadesk Audio Enabled"
    id: megadesk_audio_enabled
    device_class: sound
    lambda: |-
      if (id(megadesk_audio_enabled_raw).state == 0) {
        return false;
      }
      return true;

number:
  - platform: template
    name: "Megadesk Height (cm)"
    id: megadesk_height_cm
    min_value: 65.8
    max_value: 122.0
    step: 0.1
    mode: slider
    update_interval: never
    unit_of_measurement: 'cm'
    lambda: |-
      return ((((id(megadesk_raw).state - 300) * (122.0 - 65.8)) / (6012 - 300)) + 65.8);
    set_action:
      - number.set: 
          id: megadesk_height_raw
          value: !lambda "return int((((x - 65.8) * (6012 - 300)) / (122.0 - 65.8)) + 300);"
  
  - platform: template
    id: megadesk_height_raw
    name: Megadesk Raw
    min_value: 300
    max_value: 6012
    step: 1
    internal: true
    mode: slider
    update_interval: never
    lambda: |-
      return id(megadesk_raw).state;
    set_action:
      - uart.write: !lambda |-
          char buf[20];
          sprintf(buf, "<=%i,.", int(x));
          std::string s = buf;
          return std::vector<unsigned char>( s.begin(), s.end() );

button:
  - platform: template
    name: "Toggle Audio"
    on_press:
      then:
        - uart.write: "<L,17."
        - uart.write: "<R.17."
  - platform: template
    name: "Reboot"
    on_press:
      then:
        - uart.write: "<L,15."
  - platform: template
    name: "Sitting"
    on_press: 
      then:
        - uart.write: "<l,2."
  - platform: template
    name: "Standing"
    on_press: 
      then:
        - uart.write: "<L,2."
  - platform: template
    name: "Move Up"
    on_press: 
      then:
        - uart.write: "<+150.."
  - platform: template
    name: "Move Down"
    on_press: 
      then:
        - uart.write: "<-150.."

interval:
  - interval: 30s
    then:
      - uart.write: "<C0.0."
      - delay: 1s
      - uart.write: "<R.17."
      - delay: 1s
      - uart.write: "<R.18."
      - delay: 1s
      - uart.write: "<R.11."
      - delay: 1s
      - uart.write: "<R.12."
