esphome:
  name: megadesk
  friendly_name: Megadesk
  on_boot: 
    priority: -100
    then:
      - delay: 1s
      - uart.write: "<C0.0."
      - delay: 1s
      - uart.write: "<R0.11."
      - delay: 1s
      - uart.write: "<R0.12."
      - delay: 1s
      - uart.write: "<T2000,64."
      - delay: 0.4s
      - uart.write: "<T3000,64."
      - delay: 0.4s
      - uart.write: "<T4000,128."

esp8266:
  board: d1_mini

external_components:
  - source: github://lukepistrol/megadesk_esphome@master
    components: [megadesk]

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  ap:
    ssid: "Megadesk Fallback Hotspot"
    password: "nWMK1hYEtYzE"

captive_portal:

web_server:
  port: 80

uart:
  id: uart_desk
  baud_rate: 115200
  tx_pin: D0
  rx_pin: D1

megadesk:
  id: megadesk_controller
  uart_id: uart_desk

sensor:
  - platform: megadesk
    megadesk_id: megadesk_controller
    raw_height:
      id: megadesk_raw
      name: "Megadesk Raw"
      internal: true
      on_value:
        then:
          - component.update: megadesk_position_state
    min_height:
      name: "Minimum Height"
    max_height:
      name: "Maximum Height"

  - platform: uptime
    name: Uptime
    update_interval: 30s
    entity_category: "diagnostic"

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 30s
    entity_category: "diagnostic"

number:
  - platform: megadesk
    megadesk_id: megadesk_controller
    height:
      name: "Height"
      id: megadesk_height_cm
    height_raw:
      name: "Height (raw)"
      internal: true

switch:
  - platform: megadesk
    megadesk_id: megadesk_controller
    audio:
      name: "Enable Sounds"
    two_button:
      name: "Enable 2 Button Mode"

button:
  - platform: megadesk
    megadesk_id: megadesk_controller
    sitting:
      name: "Sitting"
    standing:
      name: "Standing"
    relaxed:
      name: "Relaxed"
    move_up:
      name: "Move Up"
    move_down:
      name: "Move Down"
    reboot:
      name: "Reboot"
    calibrate:
      name: "Calibrate"
    set_sitting:
      name: "Set Sitting Height"
    set_standing:
      name: "Set Standing Height"
    set_relaxed:
      name: "Set Relaxed Height"
    set_min_height:
      name: "Set Minimum Height"
    set_max_height:
      name: "Set Maximum Height"

text_sensor:
  - platform: template
    name: "Position"
    id: megadesk_position_state
    icon: "mdi:table-chair"
    lambda: |-
      if (id(megadesk_height_cm).state <= 90.0) {
        if (id(megadesk_height_cm).state <= 72.5) {
          return {"Sitting"};
        }
        return {"Relaxed"};
      }
      return {"Standing"};

interval:
  - interval: 30s
    then:
      - uart.write: "<C0.0."
      - uart.write: "<R.17."
      - uart.write: "<R.18."
      - uart.write: "<R.11."
      - uart.write: "<R.12."
